import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# =============================================================================
# email_agent.py
# =============================================================================
# Responsibility : Send the generated HTML report to the candidate via email.
#                 Supports two methods:
#                 1. SendGrid API  (recommended for production)
#                 2. SMTP / Gmail  (recommended for testing/personal use)
# Used by       : main.py
# Dependencies  : sendgrid, python-dotenv, smtplib (stdlib)
# =============================================================================

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from dotenv import load_dotenv


# -----------------------------------------------------------------------------
# Load environment variables from .env file
# -----------------------------------------------------------------------------

load_dotenv()


# -----------------------------------------------------------------------------
# Internal helpers
# -----------------------------------------------------------------------------

def _build_email_message(
    sender_email: str,
    recipient_email: str,
    recipient_name: str,
    job_title: str,
    html_content: str,
) -> MIMEMultipart:
    """
    Build a MIME email message with both plain text and HTML parts.
    Email clients will display the HTML version if supported,
    falling back to plain text if not.
    """
    message = MIMEMultipart("alternative")
    message["Subject"] = (
        f"Your Resume Analysis Report — {job_title}"
    )
    message["From"]    = sender_email
    message["To"]      = recipient_email

    # Plain text fallback
    plain_text = f"""
Hi {recipient_name},

Please find your resume analysis report attached below.

This report was generated by the Resume Analyzer and includes:
- Your overall match score for the role of {job_title}
- Skills matched and missing
- Work experience summary
- Education summary
- Personalised recommendations

For the best experience please view this email in an HTML-supported client.

Best regards,
Resume Analyzer
    """.strip()

    # Attach both parts — HTML takes priority in modern email clients
    message.attach(MIMEText(plain_text, "plain"))
    message.attach(MIMEText(html_content, "html"))

    return message


def _send_via_smtp(
    message: MIMEMultipart,
    sender_email: str,
    recipient_email: str,
) -> dict:
    """
    Send an email using SMTP with TLS.
    Reads credentials from environment variables:
        SMTP_HOST     — e.g. smtp.gmail.com
        SMTP_PORT     — e.g. 587
        SMTP_USER     — your email address
        SMTP_PASSWORD — your app password (not your main password)

    For Gmail:
        1. Enable 2-Factor Authentication on your Google account
        2. Go to Google Account → Security → App Passwords
        3. Generate an app password and use that as SMTP_PASSWORD
    """
    smtp_host     = os.getenv("SMTP_HOST",     "smtp.gmail.com")
    smtp_port     = int(os.getenv("SMTP_PORT", "587"))
    smtp_user     = os.getenv("SMTP_USER",     "")
    smtp_password = os.getenv("SMTP_PASSWORD", "")

    if not smtp_user or not smtp_password:
        return {
            "success": False,
            "method":  "smtp",
            "error":   (
                "SMTP credentials not found in .env file.\n"
                "Please set SMTP_USER and SMTP_PASSWORD in your .env file."
            ),
        }

    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.ehlo()
            server.starttls()                          # encrypt the connection
            server.login(smtp_user, smtp_password)
            server.sendmail(
                sender_email,
                recipient_email,
                message.as_string(),
            )

        return {
            "success":   True,
            "method":    "smtp",
            "recipient": recipient_email,
            "error":     None,
        }

    except smtplib.SMTPAuthenticationError:
        return {
            "success": False,
            "method":  "smtp",
            "error":   (
                "SMTP authentication failed. "
                "For Gmail, make sure you are using an App Password, "
                "not your regular Gmail password."
            ),
        }

    except smtplib.SMTPException as e:
        return {
            "success": False,
            "method":  "smtp",
            "error":   f"SMTP error: {str(e)}",
        }

    except Exception as e:
        return {
            "success": False,
            "method":  "smtp",
            "error":   f"Unexpected error: {str(e)}",
        }


def _send_via_sendgrid(
    sender_email: str,
    recipient_email: str,
    recipient_name: str,
    subject: str,
    html_content: str,
    plain_text: str,
) -> dict:
    """
    Send an email using the SendGrid API.
    Reads credentials from environment variables:
        SENDGRID_API_KEY — your SendGrid API key
        SENDER_EMAIL     — verified sender email in SendGrid

    To get a SendGrid API key:
        1. Sign up at sendgrid.com (free tier allows 100 emails/day)
        2. Go to Settings → API Keys → Create API Key
        3. Copy the key into your .env file
        4. Verify your sender email in SendGrid
    """
    try:
        from sendgrid import SendGridAPIClient
        from sendgrid.helpers.mail import Mail, Content, To
    except ImportError:
        return {
            "success": False,
            "method":  "sendgrid",
            "error":   "sendgrid package not installed.",
        }

    api_key = os.getenv("SENDGRID_API_KEY", "")

    if not api_key:
        return {
            "success": False,
            "method":  "sendgrid",
            "error":   (
                "SENDGRID_API_KEY not found in .env file.\n"
                "Please add your SendGrid API key to the .env file."
            ),
        }

    try:
        mail = Mail(
            from_email    = sender_email,
            to_emails     = To(recipient_email, recipient_name),
            subject       = subject,
            html_content  = Content("text/html",  html_content),
        )
        mail.add_content(Content("text/plain", plain_text))

        sg       = SendGridAPIClient(api_key)
        response = sg.send(mail)

        if response.status_code in (200, 202):
            return {
                "success":     True,
                "method":      "sendgrid",
                "recipient":   recipient_email,
                "status_code": response.status_code,
                "error":       None,
            }
        else:
            return {
                "success":     False,
                "method":      "sendgrid",
                "status_code": response.status_code,
                "error":       f"SendGrid returned status {response.status_code}",
            }

    except Exception as e:
        return {
            "success": False,
            "method":  "sendgrid",
            "error":   f"SendGrid error: {str(e)}",
        }


# -----------------------------------------------------------------------------
# Public interface
# -----------------------------------------------------------------------------

def send_report_email(
    recipient_email: str,
    recipient_name: str,
    html_report: str,
    job_title: str = "the position",
    method: str = "smtp",
) -> dict:
    """
    Main entry point. Sends the HTML report to the candidate by email.

    Parameters
    ----------
    recipient_email : str  — candidate's email address
    recipient_name  : str  — candidate's full name
    html_report     : str  — rendered HTML from report_generator.generate_report()
    job_title       : str  — name of the role being applied for
    method          : str  — 'smtp' or 'sendgrid' (default: 'smtp')

    Returns
    -------
    dict with keys:
        - success   : bool — True if email sent successfully
        - method    : str  — which method was used
        - recipient : str  — email address it was sent to
        - error     : str or None — error message if failed

    Raises
    ------
    ValueError
        If recipient_email or html_report is empty.
    """

    # 1. Validate inputs
    if not recipient_email or not recipient_email.strip():
        raise ValueError("Recipient email is empty.")

    if not html_report or not html_report.strip():
        raise ValueError("HTML report is empty. Run report_generator first.")

    if "@" not in recipient_email:
        raise ValueError(f"Invalid email address: {recipient_email}")

    # 2. Read sender email from environment
    sender_email = os.getenv("SENDER_EMAIL") or os.getenv("SMTP_USER", "")

    if not sender_email:
        return {
            "success": False,
            "method":  method,
            "error":   (
                "Sender email not found. "
                "Please set SENDER_EMAIL in your .env file."
            ),
        }

    subject = f"Your Resume Analysis Report — {job_title}"

    plain_text = (
        f"Hi {recipient_name},\n\n"
        f"Please find your resume analysis report for the role of "
        f"{job_title} below.\n\n"
        f"Best regards,\nResume Analyzer"
    )

    # 3. Route to correct sending method
    if method == "sendgrid":
        return _send_via_sendgrid(
            sender_email    = sender_email,
            recipient_email = recipient_email,
            recipient_name  = recipient_name,
            subject         = subject,
            html_content    = html_report,
            plain_text      = plain_text,
        )

    else:
        # Default to SMTP
        message = _build_email_message(
            sender_email    = sender_email,
            recipient_email = recipient_email,
            recipient_name  = recipient_name,
            job_title       = job_title,
            html_content    = html_report,
        )
        return _send_via_smtp(
            message         = message,
            sender_email    = sender_email,
            recipient_email = recipient_email,
        )


# -----------------------------------------------------------------------------
# Quick manual test
# python modules/email_agent.py
# -----------------------------------------------------------------------------

if __name__ == "__main__":

    # Read a sample HTML report from disk if it exists
    report_path = "report.html"

    if not os.path.exists(report_path):
        print(
            "No report.html found. "
            "Run python modules/report_generator.py first."
        )
        sys.exit(1)

    with open(report_path, "r", encoding="utf-8") as f:
        sample_html = f.read()

    print("\nTesting email agent...")
    print("-" * 60)
    print("NOTE: This test will attempt to send a real email.")
    print("Make sure your .env file has valid credentials first.")
    print("-" * 60)

    # Check which method to use based on available env vars
    if os.getenv("SENDGRID_API_KEY"):
        method = "sendgrid"
    else:
        method = "smtp"

    print(f"Using method: {method}")

    # Use env var for test recipient or fall back to a placeholder
    test_recipient = os.getenv("TEST_RECIPIENT_EMAIL", "test@example.com")
    test_name      = os.getenv("TEST_RECIPIENT_NAME",  "Test Candidate")

    result = send_report_email(
        recipient_email = test_recipient,
        recipient_name  = test_name,
        html_report     = sample_html,
        job_title       = "Senior Software Engineer",
        method          = method,
    )

    if result["success"]:
        print(f"Email sent successfully to: {result['recipient']}")
        print(f"Method used: {result['method']}")
    else:
        print(f"Email failed.")
        print(f"Reason: {result['error']}")
